name: Build ChargeLimiter

on: [push]

jobs:
  build:
    name: Build ChargeLimiter
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      
      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: |
          brew install make ldid dpkg

      # Step 3: Set PATH environment variable
      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      # Step 4: Cache Theos
      - name: Cache Theos
        id: theos
        uses: actions/cache@v4
        with:
          path: theos/
          key: theos-cache-${{ runner.os }}
          restore-keys: theos-cache-

      # Step 5: Setup Theos if not cached
      - name: Setup Theos
        if: steps.theos.outputs.cache-hit != 'true'
        run: |
          git clone --recursive https://github.com/theos/theos.git theos
          cd theos
          git submodule update --init --recursive

      # Step 6: Download iOS SDK
      - name: Download iOS SDK
        if: steps.theos.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk ../theos/sdks

      # Step 7: Build ChargeLimiter
      - name: Build ChargeLimiter
        run: |
          cd ChargeLimiter
          make clean package FINALPACKAGE=1
        env:
          THEOS: ${{ github.workspace }}/theos

      # Step 8: Upload the built package
      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: ChargeLimiter
          path: ChargeLimiter/packages/*.deb